### ISSUE TITLE
Use of palette not working

### ISSUE THREAD

**Issue by epabion** [tecosaur/BMC#10]
Using a pallete different from **de** makes no difference in the generated PDF.
The PDF generated with the two attached files are not visually different.

[Palette.txt](https://github.com/tecosaur/BMC/files/3800961/Palette.txt)
[PaletteFr.txt](https://github.com/tecosaur/BMC/files/3800962/PaletteFr.txt)

**Comment by tecosaur** [comment]
Ooops, sorry but this got lost in the flood of github notifications I get. I'll take a look :)

**Comment by tecosaur** [comment]
Ok. I see what the issue is. Changing the colour palette only afects `Red`, `Green`, `Purple`, etc. but not the primary colours. If you had something like
```tex
\usepalette{fr}
\colorlet{primary}{Blue}
```
Then you'd see the effect you want.

As a side note if you put that in the preamble, then `primaryVariant` will be automatically calculated, and so the "Contents" on the contents page won't look weird

![image](https://user-images.githubusercontent.com/20903656/70370082-d22a4700-18fd-11ea-88f7-c78e7224cbb9.png)
![image](https://user-images.githubusercontent.com/20903656/70370086-d9e9eb80-18fd-11ea-9ea4-ed85fe9884f2.png)
